services:
  zookeeper:
    image: focker.ir/confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hadoop-net

  journalnode:
    image: focker.ir/apache/hadoop:3.3.6
    container_name: journalnode
    hostname: journalnode
    volumes:
      - ./hadoop-config:/etc/hadoop/
      - ./hadoop-data:/hadoop/dfs
    command: tail -f /dev/null # Keep container running for manual setup
    networks:
      - hadoop-net

  namenode1:
    image: focker.ir/apache/hadoop:3.3.6
    container_name: namenode1
    hostname: namenode1
    depends_on:
      - journalnode
      - zookeeper
    ports:
      - "9870:9870" # Active NameNode UI
      - "9000:9000"
    volumes:
      - ./hadoop-config:/etc/hadoop/
      - ./data:/host-data
    command: tail -f /dev/null # Keep container running for manual setup
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    networks:
      - hadoop-net

  namenode2:
    image: focker.ir/apache/hadoop:3.3.6
    container_name: namenode2
    hostname: namenode2
    depends_on:
      - journalnode
      - zookeeper
    ports:
      - "9871:9870" # Standby NameNode UI
    volumes:
      - ./hadoop-config:/etc/hadoop/
    command: tail -f /dev/null # Keep container running for manual setup
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    networks:
      - hadoop-net

  datanode1:
    image: focker.ir/apache/hadoop:3.3.6
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode1
      - namenode2
    volumes:
      - ./hadoop-config:/etc/hadoop/
    command: tail -f /dev/null # Keep container running for manual setup
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    networks:
      - hadoop-net

  datanode2:
    image: focker.ir/apache/hadoop:3.3.6
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode1
      - namenode2
    volumes:
      - ./hadoop-config:/etc/hadoop/
    command: tail -f /dev/null # Keep container running for manual setup
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
    networks:
      - hadoop-net


  spark:
    image: focker.ir/bitnami/spark:latest
    container_name: spark
    hostname: spark
    depends_on:
      - namenode1
      - namenode2
      - datanode1
      - datanode2
    volumes:
      - ./hadoop-config:/opt/bitnami/spark/conf/
      - ./app:/app
    command: tail -f /dev/null
    networks:
      - hadoop-net

  # spark-cl:
  #   build:
  #     context: ./spark-app
  #   container_name: spark-client
  #   hostname: spark-client
  #   depends_on:
  #     - namenode1
  #     - namenode2
  #     - datanode1
  #     - datanode2
  #   volumes:
  #     - ./hadoop-config:/etc/hadoop/
  #   # Add this environment variable to tell Spark where to find HDFS configs
  #   environment:
  #     - HADOOP_CONF_DIR=/etc/hadoop
  #   command: tail -f /dev/null # Keep container running
  #   networks:
  #     - hadoop-net

  # setup-and-run:
  #   build:
  #     context: ./spark-app
  #   container_name: setup-and-run
  #   hostname: setup-and-run
  #   depends_on:
  #     - namenode1
  #     - namenode2
  #     - datanode1
  #     - datanode2
  #   volumes:
  #     - ./hadoop-config:/etc/hadoop/
  #     - ./spark-app:/app
  #     - ./setup.sh:/setup.sh
  #   command: ["/bin/bash", "/setup.sh"]
  #   networks:
  #     - hadoop-net

networks:
  hadoop-net:
    driver: bridge
